// Writes `lib/features/quran/domain/quran_structure_data.dart` from a QuranHub export.
//
// Run:
//   curl -o quran-uthmani.json https://api.quranhub.com/v1/quran/quran-uthmani
//   dart run tool/export_quran_structure.dart quran-uthmani.json
//
// Only numbers are kept (where each page, juz, hizb quarter starts, and the sajdah verses); the
// verse text in the file is ignored. The export is checked against the bundled Tanzil text: every
// sura must have the same number of verses, or nothing is written.
import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  if (args.length != 1) {
    stderr.writeln(
      'usage: dart run tool/export_quran_structure.dart <export.json>',
    );
    exit(64);
  }
  final export = jsonDecode(File(args.single).readAsStringSync()) as Map;
  final suras = ((export['data'] as Map)['surahs'] as List).cast<Map>();

  final tanzilCounts = <int, int>{};
  for (final line in File('assets/quran/quran-uthmani.txt').readAsLinesSync()) {
    if (line.startsWith('#') || line.trim().isEmpty) continue;
    final sura = int.parse(line.split('|').first);
    tanzilCounts[sura] = (tanzilCounts[sura] ?? 0) + 1;
  }
  if (suras.length != 114) _fail('expected 114 suras, found ${suras.length}');

  final pages = <int>[], juz = <int>[], quarters = <int>[], sajdah = <int>[];
  var page = 0, part = 0, quarter = 0;
  for (final sura in suras) {
    final number = sura['number'] as int;
    final ayahs = (sura['ayahs'] as List).cast<Map>();
    if (ayahs.length != tanzilCounts[number]) {
      _fail(
        'sura $number: ${ayahs.length} verses, Tanzil has ${tanzilCounts[number]}',
      );
    }
    for (var i = 0; i < ayahs.length; i++) {
      final ayah = ayahs[i];
      if (ayah['numberInSurah'] != i + 1) _fail('sura $number: verse order');
      final key = number * 1000 + i + 1;
      if (ayah['page'] != page) {
        if (ayah['page'] != page + 1) _fail('page jumps at $number:${i + 1}');
        page = ayah['page'] as int;
        pages.add(key);
      }
      if (ayah['juz'] != part) {
        if (ayah['juz'] != part + 1) _fail('juz jumps at $number:${i + 1}');
        part = ayah['juz'] as int;
        juz.add(key);
      }
      if (ayah['hizbQuarter'] != quarter) {
        if (ayah['hizbQuarter'] != quarter + 1) {
          _fail('hizb quarter jumps at $number:${i + 1}');
        }
        quarter = ayah['hizbQuarter'] as int;
        quarters.add(key);
      }
      final mark = ayah['sajda'];
      if (mark != null && mark != false && mark != 0) sajdah.add(key);
    }
  }
  if (pages.length != 604 || juz.length != 30 || quarters.length != 240) {
    _fail(
      'counts: ${pages.length} pages, ${juz.length} juz, ${quarters.length} quarters',
    );
  }

  String list(String name, String doc, List<int> values) =>
      '/// $doc\nconst $name = <int>[${values.join(', ')}];\n';
  File('lib/features/quran/domain/quran_structure_data.dart').writeAsStringSync(
    '// GENERATED by tool/export_quran_structure.dart from a QuranHub export; do not edit by hand.\n'
    '// Each value is `sura * 1000 + verse`: the first verse of that page, juz, or hizb quarter.\n'
    '// The numbers describe the Madinah mushaf layout (604 pages). They contain no Quran text.\n\n'
    '${list('pageStarts', 'The first verse of each of the 604 pages.', pages)}\n'
    '${list('juzStarts', 'The first verse of each of the 30 juz.', juz)}\n'
    '${list('hizbQuarterStarts', 'The first verse of each of the 240 hizb quarters.', quarters)}\n'
    '${list('sajdahVerses', 'The verses with a prostration (sajdah).', sajdah)}',
  );
  stdout.writeln(
    'wrote ${pages.length} pages, ${juz.length} juz, ${quarters.length} quarters, ${sajdah.length} sajdah',
  );
}

Never _fail(String message) {
  stderr.writeln('export refused: $message');
  exit(1);
}
